language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"

script:
  # Make sure everything is formatted correctly.
  - $(exit $(go fmt ./... | wc -l))

  # Record all assertions for stats.
  - $(exit $(grep -r '"github.com/stretchr/testify"' . --include \*.go | wc -l))

  # Make sure go generate is in sync.
  - cd cmd/pie && go generate
  - go install
  - cd ../../ && go generate ./...
  - $(exit $(git status --porcelain | wc -l))

  # Run tests.
  - go test -race ./pkg/pie -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
